version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4010:4010'
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    env_file: .env.docker
    depends_on:
      - postgres
      - mongo
      - redis
    # Use image default CMD (migrate deploy + start)

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: express_template
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - app
    volumes:
      - ./e2e:/app/e2e
      - ./playwright-report:/app/playwright-report

volumes:
  postgres_data:
  mongo_data:
  redis_data:
