name: E2E Tests (Docker)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Cache Playwright binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Start E2E stack
        run: docker compose -f docker-compose.yml -f docker-compose.e2e.yml up -d --build

      - name: Seed databases
        run: npm run seed

      - name: Run Playwright tests
        env:
          BASE_URL: http://localhost:4010
          PLAYWRIGHT_WORKERS: 1
        run: npx playwright test -c playwright.e2e.config.ts

      - name: Teardown stack
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.e2e.yml down -v

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
